### ISSUE TITLE
Correggere errore tipografico

### ISSUE THREAD

**Issue by ValeriaV** [emergenzeHack/terremotocentroitalia-bot-telegram#3]
Il bot di benvenuto con il link alle issue riporta questo testo:

> `Benvenuta/o @[username] se vuoi sapere **costa** stiamo facendo, fai click qui `

Sarebbe da correggere "costa" in "cosa".

**Comment by aborruso** [comment]
@ValeriaV non avevo capito nulla e ti ho indirizzato nel repository sbagliato. 

Scusatemi tutti. Vado a correggere quanto scritto da @ValeriaV
